name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Descargar el archivo coverage.xml desde el artefacto
      - name: Download coverage.xml artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report

      # Paso 3: Verificar que coverage.xml esté presente
      - name: Debug coverage.xml
        run: ls -l coverage.xml

      # Paso 4: Análisis en SonarCloud
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=OmarGarciaTorres_Aseguramiento-de-la-Calidad-del-Software
            -Dsonar.organization=omar1
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=.
