name: CI with SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test-and-analyze:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Checkout del código
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Fetch full history para blame (opcional pero recomendado)
      - name: Fetch full history for blame
        run: git fetch --unshallow

      # Paso 3: Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Paso 4: Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Paso 5: Ejecutar pruebas unitarias con cobertura
      - name: Run Tests with Coverage
        run: |
          pytest --cov=example --cov-report=term-missing

      # Paso 6: Debug coverage.xml para verificar paths
      - name: Debug coverage.xml
        run: cat coverage.xml

      # Paso 7: Análisis en SonarCloud
      - name: SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=OmarGarciaTorres_Aseguramiento-de-la-Calidad-del-Software
            -Dsonar.organization=omar1
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
